[package]
name = "elkodon_bb_testing"
description = "Elkodon: simple testing primitives"
rust-version = { workspace = true }
version = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
elkodon_pal_settings = { workspace = true }
